# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_webview.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(844, 640)
        MainWindow.setMinimumSize(QtCore.QSize(844, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.webView = QtWebKitWidgets.QWebView(self.centralwidget)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout.addWidget(self.webView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rb_fileInput = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_fileInput.setMinimumSize(QtCore.QSize(90, 0))
        self.rb_fileInput.setMaximumSize(QtCore.QSize(160, 16777215))
        self.rb_fileInput.setChecked(True)
        self.rb_fileInput.setObjectName("rb_fileInput")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb_fileInput)
        self.horizontalLayout_7.addWidget(self.rb_fileInput, 0, QtCore.Qt.AlignLeft)
        self.pb_load = QtWidgets.QPushButton(self.centralwidget)
        self.pb_load.setObjectName("pb_load")
        self.horizontalLayout_7.addWidget(self.pb_load, 0, QtCore.Qt.AlignLeft)
        self.pb_plot = QtWidgets.QPushButton(self.centralwidget)
        self.pb_plot.setObjectName("pb_plot")
        self.horizontalLayout_7.addWidget(self.pb_plot, 0, QtCore.Qt.AlignLeft)
        self.pb_exportPlot = QtWidgets.QPushButton(self.centralwidget)
        self.pb_exportPlot.setObjectName("pb_exportPlot")
        self.horizontalLayout_7.addWidget(self.pb_exportPlot)
        self.pb_exportBits = QtWidgets.QPushButton(self.centralwidget)
        self.pb_exportBits.setObjectName("pb_exportBits")
        self.horizontalLayout_7.addWidget(self.pb_exportBits)
        spacerItem = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.rb_textInput = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_textInput.setMinimumSize(QtCore.QSize(80, 0))
        self.rb_textInput.setMaximumSize(QtCore.QSize(90, 16777215))
        self.rb_textInput.setObjectName("rb_textInput")
        self.buttonGroup.addButton(self.rb_textInput)
        self.horizontalLayout_12.addWidget(self.rb_textInput, 0, QtCore.Qt.AlignLeft)
        self.le_textInput = QtWidgets.QLineEdit(self.centralwidget)
        self.le_textInput.setEnabled(False)
        self.le_textInput.setObjectName("le_textInput")
        self.horizontalLayout_12.addWidget(self.le_textInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 8, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_digitalBits = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_digitalBits.setEnabled(True)
        self.cb_digitalBits.setChecked(True)
        self.cb_digitalBits.setObjectName("cb_digitalBits")
        self.horizontalLayout_2.addWidget(self.cb_digitalBits)
        self.cb_nrz = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_nrz.setObjectName("cb_nrz")
        self.horizontalLayout_2.addWidget(self.cb_nrz)
        self.cb_b8zs = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_b8zs.setObjectName("cb_b8zs")
        self.horizontalLayout_2.addWidget(self.cb_b8zs)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.rb_textInput.toggled['bool'].connect(self.le_textInput.setEnabled)
        self.rb_fileInput.toggled['bool'].connect(self.pb_load.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Encoder"))
        self.rb_fileInput.setText(_translate("MainWindow", "File Input"))
        self.pb_load.setText(_translate("MainWindow", "Load"))
        self.pb_plot.setText(_translate("MainWindow", "Plot"))
        self.pb_exportPlot.setText(_translate("MainWindow", "Export Plot"))
        self.pb_exportBits.setText(_translate("MainWindow", "Export Bitstream"))
        self.rb_textInput.setText(_translate("MainWindow", "Text Input"))
        self.label.setText(_translate("MainWindow", "Encoding:"))
        self.cb_digitalBits.setText(_translate("MainWindow", "RAW"))
        self.cb_nrz.setText(_translate("MainWindow", "NRZ Unipolar"))
        self.cb_b8zs.setText(_translate("MainWindow", "B8ZS"))
from PyQt5 import QtWebKitWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
